cc_test(
    name = "structured_bindings",
    srcs = [
        "enable_structured_binding.cpp",
        "structured_bindings.cpp",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
