cc_test(
    name = "string_literals_as_template_params",
    srcs = ["string_literals_as_template_params.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
